# Generated by Django 3.0.3 on 2020-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200420_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='findbusiness',
            name='clas',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
