# Generated by Django 3.0.3 on 2020-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_findbusiness_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='findbusiness',
            name='clas',
            field=models.CharField(max_length=30),
        ),
    ]
