# Generated by Django 3.0.3 on 2020-04-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200413_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findbusiness',
            old_name='title',
            new_name='category',
        ),
    ]
