# Generated by Django 3.0.3 on 2020-04-26 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200424_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_list',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
