# Generated by Django 3.0.3 on 2020-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_donormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_register',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
