# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('album', models.CharField(max_length=20)),
                ('extra', models.CharField(max_length=20)),
            ],
        ),
    ]
