# Generated by Django 2.2 on 2020-03-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
