# Generated by Django 2.2 on 2020-03-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_videos_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
